INSERT INTO video_game (title, genre, release_date, developer, publisher)
VALUES
    ('Cyberpunk 2077', 'RPG', 2020, 'CD Projekt Red', 'CD Projekt'),
    ('The Witcher 3: Wild Hunt', 'RPG', 2015, 'CD Projekt Red', 'CD Projekt'),
    ('Minecraft', 'Sandbox', 2011, 'Mojang', 'Mojang'),
    ('Grand Theft Auto V', 'Action-Adventure', 2013, 'Rockstar North', 'Rockstar Games'),
    ('The Legend of Zelda: Breath of the Wild', 'Action-Adventure', 2017, 'Nintendo', 'Nintendo'),
    ('Red Dead Redemption 2', 'Action-Adventure', 2018, 'Rockstar Studios', 'Rockstar Games'),
    ('Fortnite', 'Battle Royale', 2017, 'Epic Games', 'Epic Games'),
    ('Among Us', 'Social Deduction', 2018, 'InnerSloth', 'InnerSloth'),
    ('Counter-Strike: Global Offensive', 'First-Person Shooter', 2012, 'Valve', 'Valve'),
    ('Apex Legends', 'Battle Royale', 2019, 'Respawn Entertainment', 'Electronic Arts'),
    ('Fallout 4', 'RPG', 2015, 'Bethesda Game Studios', 'Bethesda Softworks'),
    ('Overwatch', 'First-Person Shooter', 2016, 'Blizzard Entertainment', 'Blizzard Entertainment'),
    ('League of Legends', 'MOBA', 2009, 'Riot Games', 'Riot Games'),
    ('The Elder Scrolls V: Skyrim', 'RPG', 2011, 'Bethesda Game Studios', 'Bethesda Softworks'),
    ('Rainbow Six Siege', 'Tactical Shooter', 2015, 'Ubisoft Montreal', 'Ubisoft'),
    ('Rocket League', 'Sports', 2015, 'Psyonix', 'Psyonix'),
    ('Stardew Valley', 'Simulation', 2016, 'ConcernedApe', 'ConcernedApe'),
    ('Sekiro: Shadows Die Twice', 'Action-Adventure', 2019, 'FromSoftware', 'Activision'),
    ('Hades', 'Roguelike', 2020, 'Supergiant Games', 'Supergiant Games'),
    ('Dark Souls III', 'Action RPG', 2016, 'FromSoftware', 'Bandai Namco Entertainment'),
    ('Cyber Shadow', 'Platformer', 2021, 'Mechanical Head Studios', 'Yacht Club Games'),
    ('Death Stranding', 'Action', 2019, 'Kojima Productions', 'Sony Interactive Entertainment'),
    ('Doom Eternal', 'First-Person Shooter', 2020, 'id Software', 'Bethesda Softworks'),
    ('Hollow Knight', 'Metroidvania', 2017, 'Team Cherry', 'Team Cherry'),
    ('Celeste', 'Platformer', 2018, 'Maddy Makes Games', 'Maddy Makes Games');